version: "2"
services:

  redis:
    image: redis
#    command: ["redis-server", "--appendonly", "yes"]
#    ports:
#      - 6379:6379
    network_mode: host
    volumes:
    - redis-data:/data

  core:
    build:
      context: gc_core
      dockerfile: ../docker/core/Dockerfile
    network_mode: host
    environment:
      - APP_WITH_REDIS=1
    volumes:
      - "./gc_core/gc_core:/app/gc_core"

volumes:
  redis-data: